# Generated by Django 2.0.3 on 2018-03-27 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180326_2134'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizScore',
            new_name='Quiz',
        ),
    ]
