# Generated by Django 2.0.3 on 2018-03-23 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super_user',
            old_name='last_name',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='super_user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='super_user',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
